wmde/FundraisingStore

src/Entities/ActionLog.php, src/Entities/BackendBanner.php, src/Entities/BackendImpressions.php, src/Entities/Request.php, src/Entities/Spenden.php, src/Entities/Users.php, tests/integration/AutoloaderTest.php
Copied from the fundraising frontent repo at 536de4a3de0641c384b633d7493fd35e204e68ba
=> Move over copy of the fundraising entities

README.md, src/Entities/ActionLog.php, src/Entities/BackendBanner.php, src/Entities/BackendImpressions.php, src/Entities/Request.php, src/Entities/Spenden.php, src/Entities/Users.php, src/Store/Factory.php, src/Store/Installer.php
Once we merge this and then tag it, we'll be able to require that version in the frontend and backend rather than work against master. Until then it is essentially impossible to make breaking changes in this repo.
=> 0.1 release

.gitignore, cli-config.php, config.ini.template, src/Store/EntityManagerProvider.php, src/Store/Factory.php
This is based on https://github.com/wmde/fundraising/commit/3815311e99a4b2e64d0ad17ab9763d8e6bd11003 by @WMDE-Fisch.
=> Add cli-config.php, so Doctrine's console could be used

src/Store/Factory.php, src/Store/Updater.php, tests/integration/DatabaseUpdateTest.php
Follow up to https://github.com/wmde/FundraisingStore/pull/11
=> Small changes to the new Updater related code

src/Entities/ActionLog.php, src/Entities/BackendBanner.php, src/Entities/BackendImpressions.php, src/Entities/Request.php, src/Entities/Users.php
while writing the tests for missing columns I found missing defaults leading to failures
=> add defaults to non nullable columns

src/Entities/ActionLog.php, tests/integration/DatabaseUpdateTest.php
current settings were causing problems with mysql
default timestamp is now NOW()
had to change test
=> changed timestamp default

src/Entities/Donation.php, src/Entities/Membership.php, tests/integration/MembershipInsertionTest.php
The unspecific `Inquiry` is now called `Membership` which reflects the
purpose of this table better.
Fixed the `@return` statements in the doc comments of `Donation`.
Renamed test class and method to match the new class names.
=> Improve naming

README.md, composer.json, src/Entities/Donation.php, src/Entities/Membership.php, src/Entities/Subscription.php, src/Store/Factory.php
Add createdAt and updatedAt fields with a trait. The fields will be
set automatically when the entity is saved.
=> Add timestamps to Subscription

src/Entities/ActionLog.php, src/Entities/Address.php, src/Entities/BackendBanner.php, src/Entities/BackendImpression.php, src/Entities/Membership.php, src/Entities/Subscription.php, src/Entities/User.php
As in https://github.com/wmde/FundraisingStore/commit/03e6bec1ff3674e52cb173a3c9ae0181afdb5ac0
=> Use @return self in all Entity classes

src/Entities/Donation.php
This field can be null. I think. Please double check
=> Correct documentation

composer.json, src/Entities/Donation.php, tests/unit/DonationTest.php
=> Added Donation::getDecodedData and Donation::encodeAndSetData

src/Entities/Donation.php, src/Store/DonationData.php, tests/unit/DonationTest.php
The idea if to add things to this object as we find out
we want more convenient access to them.
=> Added DonationData with initial fields for token info

phpmd.xml, src/Entities/Donation.php, tests/unit/DonationTest.php
As per discussion on #36
Includes https://github.com/wmde/FundraisingStore/pull/62
=>  	Added Donation::modifyDataObject

tests/integration/MembershipApplicationInsertionTest.php
Following renaming in https://github.com/wmde/FundraisingStore/pull/64
=> Rename test involving MembershipApplication

src/Entities/MembershipApplication.php
As far as I can tell this was added just for the local usages it has
=> Make setNameFromParts private

src/Entities/MembershipApplication.php
Fixes #73
I left some things alone, as I'm not sure what they are. See questions in #75
=> Improved naming of MembershipApplication

src/Entities/Donation.php, src/Entities/MembershipApplication.php, tests/unit/DonationTest.php, tests/unit/MembershipApplicationTest.php
Includes https://github.com/wmde/FundraisingStore/pull/77
=>  	Added STATUS_ constants to Donation

.travis.yml
Test all PHP versions with all databases
=> Adjust Travis test matrix

.travis.yml
PRs #87 and #88 concurrently changed the travis config, which messed it up a little.
=> fix php version mismatch

README.md, composer.json
Follow up to https://github.com/wmde/FundraisingStore/pull/104
=> Bumped version to 3.x

README.md, src/Entities/Subscription.php, tests/unit/SubscriptionTest.php
This is for https://github.com/wmde/fundraising/issues/1110
=> Added `source` field to `subscriptions` table.

README.md
Fixes https://github.com/wmde/FundraisingStore/issues/113
=> 3.0.0 release

src/Entities/MembershipApplication.php
related to wmde/fundraising#1164
=> doubled the maximum length of bank_name

.travis.yml, README.md, composer.json, src/Entities/Donation.php, src/Entities/MembershipApplication.php
Add full text indices for name, email and city in donation and
membership tables.
This is for https://github.com/wmde/fundraising/issues/1241
=> Add fulltext indices

COPYING
filed copied over from https://github.com/wmde/FundraisingFrontend
Did not read the whole thing.
=> Added license

src/Entities/DonationPayments/SofortPayment.php, src/Entities/Payments/SofortPayment.php, tests/integration/DatabaseInstallationTest.php, tests/integration/SofortPaymentTest.php
For https://phabricator.wikimedia.org/T167886
=> Added SofortPayment Doctrine Entity

Dockerfile, README.md, docker-compose.yml, local-db-config.php
Added docker-compose based development environment to satisfy unspecified platform requirements and services.
=> T167886 docker-based development environment

src/Entities/Donation.php, src/Entities/DonationPayments/SofortPayment.php, tests/integration/SofortPaymentTest.php
Use (optional) centrally stored bank code instead of a redundant type specific properties. As discussed.
=> T167886 Use centrally stored bank code

src/Entities/DonationPayments/SofortPayment.php, tests/integration/SofortPaymentTest.php, tests/unit/DonationPayments/SofortPaymentTest.php
* php 7.1-compatible nullable style
* cleaned up tests
=> T167886 Sofort confirmedAt nullable

README.md, composer.json, src/Entities/MembershipApplication.php, tests/integration/MembershipApplicationInsertionTest.php, tests/unit/MembershipApplicationTest.php
Introduce `MembershipApplication::setDonationReceipt()` et al.
Requires `vendor/bin/doctrine orm:schema-tool:update`
=> T177416 Opt out of donation receipt - membership

Dockerfile, README.md, composer.json, src/Entities/AddressChange.php, src/Entities/Donation.php, src/Entities/MembershipApplication.php, src/Store/DonationData.php, tests/unit/AddressChangeTest.php
https://phabricator.wikimedia.org/T196333
=> Create AddressChange entity

migrations/Version20180612000000.php
=> Fix potential DB pagination issue

src/Entities/User.php
=> Update length of password field

README.md, migrations/Version20190109000000.php, src/Entities/AddressChange.php
=> Remove Third Party Identifier after change of reqs

README.md, migrations/Version20190109000000.php, src/Entities/AddressChange.php
https://phabricator.wikimedia.org/T214916
=> Add timestamps to AddressChange

src/Entities/AddressChange.php
=> Allow getAddress to return null in AddressChange

migrations/Version20190524000000.php, src/Entities/Address.php, src/Entities/AddressChange.php
[T223056](https://phabricator.wikimedia.org/T223056)
=> Donation Receipt Opt In

README.md
For [T223056](https://phabricator.wikimedia.org/T223056)
=> Add new release note

README.md, src/Entities/AddressChange.php
Change it to true to match the default of the Model in the AddressChange domain.
=> Change donationReceipt default to true
